version: "3.8"
services:
  prometheus: 
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports: 
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports: 
      - 4000:3000
    volumes:
      - ./grafana:/etc/grafana
  usgs-python:
    build:
      context: .
    ports: 
      - 8000:8000
    
