scrape_configs:
  - job_name: 'usgs'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['usgs-python:8000']
        labels:
          group: 'production'